### ISSUE TITLE
Wrong nearest intersection with firstHitOnly=true 

### ISSUE THREAD

**Issue by Filyus** [gkjohnson/three-mesh-bvh#140] opened 2020-06-18 09:03 UTC
Sometimes with firstHitOnly=true this library returns the wrong nearest intersection. With firstHitOnly=false there is no such problem, but I don't need all the intersections. Perhaps this was done for speed, but is there a compromise?
The SAH strategy is used.

**Comment by gkjohnson** [comment] 2020-06-18 17:34
Hey @Filyus! Thanks for the report. Can you put together a simple example to demonstrate the problem?

**Comment by gkjohnson** [comment] 2020-06-26 20:32
@Filyus I wanted to check in again about a repro case. Unfortunately I can't address the issue if I can reproduce it myself and the problem isn't present in the tests and demo scene.

**Comment by gkjohnson** [comment] 2020-07-02 08:46
Closing because I don't have enough data to reproduce the problem with. Feel free to open another issue with more information.

**Closed by gkjohnson** 2020-07-02 08:46 UTC
Labels: bug
