### ISSUE TITLE
./node_modules/three-mesh-bvh/src/index.js  Module parse failed: Unexpected token (12:9)

### ISSUE THREAD

**Issue by enjoyaday** [gkjohnson/three-mesh-bvh#669] opened 2024-05-31 01:31 UTC
ERROR  Failed to compile with 1 error                                                                                                         上午9:18:22

 error  in ./node_modules/three-mesh-bvh/src/index.js

Module parse failed: Unexpected token (12:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export * from './gpu/VertexAttributeTexture.js';
| export * from './utils/StaticGeometryGenerator.js';
> export * as BVHShaderGLSL from './gpu/BVHShaderGLSL.js';
|
| // backwards compatibility

 @ ./node_modules/soonspacejs/dist/index.esm.js 1:5098-5213 11:416403-416405 11:595220-595222 11:595253-595255 11:595277-595279
 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/vue-soonspace/vue-soonspace.vue?vue&type=script&lang=js
 @ ./src/components/vue-soonspace/vue-soonspace.vue?vue&type=script&lang=js
 @ ./src/components/vue-soonspace/vue-soonspace.vue
 @ ./src/components/vue-soonspace/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:7013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

"dependencies": {
    "@ant-design/icons-vue": "^6.1.0",
    "@mars3d/heatmap.js": "^2.0.6",
    "@soonspacejs/plugin-clipping-controls": "2.9.2",
    "@soonspacejs/plugin-drawing-shape": "2.9.2",
    "@soonspacejs/plugin-drawing-topology": "2.9.2",
    "@soonspacejs/plugin-first-person-controls": "2.9.2",
    "@soonspacejs/plugin-follow-mouse": "2.9.2",
    "@soonspacejs/plugin-heat-map": "2.9.2",
    "@soonspacejs/plugin-patrol-controls": "2.9.2",
    "@soonspacejs/plugin-soonmanager-sync": "2.9.2",
    "@soonspacejs/plugin-sspx": "2.9.2",
    "@soonspacejs/plugin-transform-controls": "2.9.2",
    "ant-design-vue": "^3.2.3",
    "axios": "^0.24.0",
    "cesium": "1.95.0",
    "dayjs": "^1.10.6",
    "default-passive-events": "^2.0.0",
    "echarts": "^5.1.2",
    "echarts-gl": "^2.0.9",
    "flv.js": "^1.6.2",
    "lodash": "^4.17.21",
    "mitt": "^3.0.0",
    "moment": "^2.29.1",
    "pinia": "^2.0.11",
    "print-js": "^1.6.0",
    "qs": "^6.10.3",
    "soonspacejs": "^2.9.2",
    "three": ">=0.155.0",
    "vue": ">=3.1.0",
    "vue-echarts": "^6.0.0",
    "vue-router": "^4.0.12",
    "vue-soonspace": "2.x",
    "vue3-storage": "^0.1.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": ">=3.1.0",
    "babel-eslint": "^10.1.0",
    "babel-plugin-import": "^1.13.3",
    "core-js": "^3.23.3",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "less": "^4.1.1",
    "less-loader": "^7.3.0",
    "svg-sprite-loader": "^6.0.11",
    "webpack-bundle-analyzer": "^4.5.0"
  }

**Comment by gkjohnson** [comment] 2024-05-31 01:35
Duplicate of #668 

`export * as` is valid syntax. Please report the issue to your bundler repo.

**Closed by gkjohnson** 2024-05-31 01:35 UTC
Labels: bug

**Comment by Fate-ui** [comment] 2025-08-26 01:45
configuring the following code in `vue.config.js` solved my problem
`  transpileDependencies: ['three-mesh-bvh']
`
