### ISSUE TITLE
some meshes are ignored during intersection detection

### ISSUE THREAD

**Issue by hichemfantar** [gkjohnson/three-mesh-bvh#721] opened 2024-09-27 13:07 UTC
**Describe the bug**

some intersected meshes are not detected

**To Reproduce**

3. See error

***Code***

```js
// code goes here
```

***Live example***

-

**Expected behavior**

camera should zoom in when the tree is between the character and the camera

**Screenshots**

https://github.com/user-attachments/assets/96ef66ff-9385-4daf-ba5f-e99ad74bc1ce

https://github.com/user-attachments/assets/2a9630d5-d5f7-4245-8780-0ae80dcf309c

**Platform:**

 - Device: Desktop
 - OS: Windows 
 - Browser: Chrome
 - Three.js version: three@0.165.0
 - Library version: [v0.7.8](https://github.com/gkjohnson/three-mesh-bvh/releases/tag/v0.7.8)

**Comment by gkjohnson** [comment] 2024-09-27 14:44
Hello! Please provide a minimal editable be demonstrating the issue, as the template requests, otherwise there's no way to confirm where the issue is. Closing in the meantime

**Closed by gkjohnson** 2024-09-27 14:44 UTC
Labels: bug
